FKSC/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^filiados/', include('filiados.urls')),
    url(r'^campeonatos/', include('campeonatos.urls')),
    url(r'^', include('inicial.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^ranking/', include('ranking.urls')),
    url(r'^convocados/', include('convocados.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campeonatos/urls.py
from django.conf.urls import url
from . import views

app_name = 'campeonatos'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

convocados/urls.py
from django.conf.urls import url
from . import views

app_name = 'convocados'

urlpatterns = [
    # /convocados/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /convocados/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

filiados/urls.py
from django.conf.urls import url
from . import views

app_name = 'filiados'

urlpatterns = [
    # /filiados/
    url(r'^$', views.index, name='index'),

    # /filiados/academias/
    url(r'^academias/$', views.academias, name='academias'),

    # /filiados/atletas/
    url(r'^atletas/$', views.atletas, name='atletas'),

    # /filiados/pretas/
    url(r'^pretas/$', views.pretas, name='pretas'),
]

inicial/urls.py
from django.conf.urls import url
from . import views

app_name = 'inicial'

urlpatterns = [
    #
    url(r'^$', views.index, name='index'),
]

ranking/urls.py
from django.conf.urls import url
from . import views

app_name = 'ranking'

urlpatterns = [
    # /ranking/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /ranking/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

videos/urls.py
from django.conf.urls import url
from . import views

app_name = 'videos'

urlpatterns = [
    # /videos/
    url(r'^$', views.index, name='index'),
]

campeonatos/models.py
from django.db import models

class Campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    endereco = models.CharField(max_length=500)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

convocados/models.py
from django.db import models

class Convocado_campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

class Convocados(models.Model):
    Convocado_campeonato = models.ForeignKey(Convocado_campeonato, on_delete=models.CASCADE)
    nome = models.CharField(max_length=500)
    academia = models.CharField(max_length=200)
    faixa = models.CharField(max_length=100)
    reg_fed = models.IntegerField()

    def __str__(self):
        return self.nome

filiados/models.py
from django.db import models

class Academia(models.Model):
    professor = models.CharField(max_length=100)
    nome_academia = models.CharField(max_length=200)
    estado = models.CharField(max_length=50)
    cidade = models.CharField(max_length=50)
    rua = models.CharField(max_length=200)
    bairro = models.CharField(max_length=200)
    cep = models.IntegerField()
    num_reg = models.IntegerField(default=1)

    def __str__(self):
        return self.nome_academia +' - '+ self.cidade

class Atleta(models.Model):
    nome_atleta = models.CharField(max_length=100)
    academia = models.CharField(max_length=200)
    num_reg = models.IntegerField()

    def __str__(self):
        return self.nome_atleta

class Preta(models.Model):
    nome_preta = models.CharField(max_length=100)
    academia = models.CharField(max_length=200)
    num_reg = models.IntegerField()

    def __str__(self):
        return self.nome_preta

inicial/models.py
from django.db import models

# Create your models here.

ranking/models.py
from django.db import models

class Rank_campeonato(models.Model):
    nome_campeonato = models.CharField(max_length=400)
    est_cidade = models.CharField(max_length=100)
    data = models.CharField(max_length=50)
    cartaz = models.FileField(default='/static/images/logo.jpg')

    def __str__(self):
        return self.nome_campeonato

class Categoria(models.Model):
    rank_campeonato = models.ForeignKey(Rank_campeonato, on_delete=models.CASCADE)
    idade = models.CharField(max_length=100)
    faixa = models.CharField(max_length=100)
    sexo = models.CharField(max_length=50)
    modalidade = models.CharField(max_length=50)
    primeiro = models.CharField(max_length=200)
    acad_primeiro = models.CharField(max_length=200)
    segundo = models.CharField(max_length=200)
    acad_segundo = models.CharField(max_length=200)
    terceiro = models.CharField(max_length=200)
    acad_terceiro = models.CharField(max_length=200)

    def __str__(self):
        return self.idade +'/'+ self.faixa +'/'+ self.sexo +'/'+ self.modalidade

videos/models.py
from django.db import models

class Video(models.Model):
    titulo = models.CharField(max_length=200)
    link = models.CharField(max_length=500)

    def __str__(self):
        return self.titulo

campeonatos/views.py
from django.shortcuts import render
from django.views import generic
from .models import Campeonato

class IndexView(generic.ListView):
    template_name = 'campeonatos/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Campeonato.objects.all()

convocados/views.py
from django.views import generic
from .models import Convocado_campeonato

class IndexView(generic.ListView):
    template_name = 'convocados/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Convocado_campeonato.objects.all()

class DetailView(generic.DetailView):
    model = Convocado_campeonato
    template_name = 'convocados/detail.html'

filiados/views.py
from .models import Academia, Atleta, Preta
from django.shortcuts import render

def index(request):
    return render(request, 'inicial/index.html')

def ordenar_num(lista):
    for i in range(0,len(lista)):
        for j in range(i,len(lista)):
            if lista[i] >= lista[j]:
                lista[i], lista[j] = lista[j], lista[i]
    return lista

def ordenar(todas_academias):
    lista = []
    for academia in todas_academias:
        lista = lista + [academia.num_reg]
    num_organizados = ordenar_num(lista)
    nova_lista_academias = []
    for reg in num_organizados:
        for academia in todas_academias:
            if reg == academia.num_reg:
                nova_lista_academias = nova_lista_academias + [academia]
    return nova_lista_academias

def academias(request):
    todas_academias = Academia.objects.all()
    return render(request,'filiados/academias.html', {'todas_academias': ordenar(todas_academias)})

def atletas(request):
    todos_atletas = Atleta.objects.all()
    return render(request, 'filiados/atletas.html', {'todos_atletas': ordenar(todos_atletas)})

def pretas(request):
    todos_pretas = Preta.objects.all()
    return render(request, 'filiados/pretas.html', {'todos_pretas': ordenar(todos_pretas)})

inicial/views.py
from django.shortcuts import render

def index(request):
    return render(request,'inicial/index.html')

ranking/views.py
from django.views import generic
from .models import Rank_campeonato

class IndexView(generic.ListView):
    template_name = 'ranking/index.html'
    context_object_name = 'todos_campeonatos'

    def get_queryset(self):
        return Rank_campeonato.objects.all()

class DetailView(generic.DetailView):
    model = Rank_campeonato
    template_name = 'ranking/detail.html'

videos/views.py
from django.shortcuts import render
from .models import Video

def index(request):
    todos_videos = Video.objects.all()
    return render(request, 'videos/index.html', {'todos_videos': todos_videos})

filiados/templates/filiados/academias.html
{% extends 'inicial/base.html' %}
{% block head %}
    {% load staticfiles %}
{% endblock %}
{% block body %}

            <!--========== PROMO BLOCK ==========-->
        <div class="g-fullheight--xs js__parallax-window" style="background: url({% static 'inicial/img/1920x1080/dojo.jpg' %}) 50% 0 no-repeat fixed; background-size: cover;">
            <div class="g-container--md g-ver-center--xs g-text-center--xs">
                <div class="g-margin-b-70--xs">
                    <h1 class="g-font-size-55--sm g-font-size-70--lg g-font-family--playfair g-color--primary g-margin-b-20--xs g-margin-b-40--sm">Academias de Alta Qualidade</h1>
                    <p class="g-font-size-18--xs g-font-size-20--sm g-font-size-24--lg g-color--white g-margin-b-0--xs">Você pode conferir todas as Academias que estão Registradas a Federação de Karatê Semi Contato. Se o nome da sua Academia não está aqui, filie-se já!</p>
                </div>
                <a href="#js__scroll-to-section" class="text-uppercase s-btn s-btn-icon--md s-btn--primary-brd g-radius--50 g-padding-x-60--xs">Filie-se</a>
            </div>
            <a href="http://keenthemes.com/" class="s-scroll-to-section-v1--bc g-margin-b-15--xs">
                <span class="g-font-size-18--xs g-color--white ti-angle-double-down"></span>
                <p class="text-uppercase g-font-family--playfair g-color--white g-letter-spacing--3 g-margin-b-0--xs">Confira as Academias Filiadas</p>
            </a>
        </div>
        <!--========== END PROMO BLOCK ==========-->

        <!--========== PAGE CONTENT ==========-->
        <!-- About -->
        <div id="js__scroll-to-section" class="container g-padding-y-80--xs g-padding-y-125--sm g-margin-b-25--xs">
            <div class="row g-hor-centered-row--md">
                <div class="col-md-8 g-hor-centered-row__col g-margin-b-60--xs g-margin-b-0--md">
                    <div class="g-width-100-percent--xs g-width-400--md g-margin-b-40--xs">
                        <h2 class="g-font-size-32--xs g-font-size-36--md g-font-family--playfair g-margin-b-20--xs">Nós somos <br>Líderes no Karatê</h2>
                        <p class="g-font-size-16--sm">Mantenha a sua Academia com registro em dia, isso te ajudará a ter reconhecimento dos patrocinadores.</p>
                        <p class="g-font-size-16--sm">Mostre para os seus patrocinadores que a sua Academia possui Alvará.</p>
                    </div>
                    <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".5s">
                        <div class="g-position--overlay g-text-left--xs g-text-right--md g-margin-t-o-50--lg">
                            <span class="g-font-size-60--xs g-font-size-80--sm g-font-size-105--lg g-font-family--playfair g-color--primary g-line-height--xs">21</span>
                            <span class="text-uppercase g-display-block--xs g-font-size-34--xs g-font-size-40--sm g-font-size-50--lg g-font-weight--700 g-font-family--playfair g-color--primary g-line-height--xs">Anos</span>
                            <p class="g-font-size-18--xs g-font-size-20--lg">de Experiência</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-6 col-xs-offset-3 g-full-width--xs g-full-width-offset-0--xs g-hor-centered-row__col">
                    <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".1s">
                        <img class="img-responsive" src="{% static 'inicial/img/450x700/mdeliokanazawa.jpg' %}" alt="Image">
                    </div>
                </div>
            </div>
        </div>
        <!-- End About -->

    <!-- Tabela das Academias Filiadas -->

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="panel panel-default"
                 <div class="panel-body">
                     <h3>Academias Filiadas - 2017</h3>
                     <table class="table">
                         <thead>
                         <tr>
                             <th>Academia</th>
                             <th>Estado</th>
                             <th>Cidade</th>
                             <th>Professor</th>
                             <th>Registro</th>
                         </tr>
                         </thead>
                         <tbody>
                         {% for academia in todas_academias %}
                         <tr>
                             <td>{{ academia.nome_academia }}</td>
                             <td>{{ academia.estado }}</td>
                             <td>{{ academia.cidade }}</td>
                             <td>{{ academia.professor }}</td>
                             <td>{{ academia.num_reg }}</td>
                         </tr>
                         {% endfor %}
                         </tbody>
                     </table>
                 </div>
            </div>
        </div>



    <!-- Final da Tabela das Academias Filiadas -->

    <!-- News -->
        <div class="container g-padding-y-80--xs g-padding-y-125--sm">
            <div class="g-text-center--xs g-margin-b-80--xs">
                <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2 g-margin-b-25--xs">Blog</p>
                <h2 class="g-font-size-32--xs g-font-size-36--md">Últimas Notícias</h2>
            </div>
            <div class="row">
                <div class="col-sm-4 g-margin-b-30--xs g-margin-b-0--md">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/1920x1080/copadapaz.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Notícias</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'campeonatos:index' %}">IX Copa da Paz.</a></h3>
                            <p>Um campeonato de magnitude Internacional que será sediado no Brasil.</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
                <div class="col-sm-4 g-margin-b-30--xs g-margin-b-0--md">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/1920x1080/filie.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Informativos</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'filiados:atletas' %}">Como me filiar?</a></h3>
                            <p>E agora? Desejo me filiar ou filiar os meus alunos, como faço? Clica e descubra</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
                <div class="col-sm-4">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/970x970/brasileiro2017.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Notícias</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'campeonatos:index' %}">XXI Campeonato Brasileiro Inter Clubes.</a></h3>
                            <p>Descubra o sucesso que foi participar do Campeonato Brasileiro de 2017.</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
            </div>
        </div>
        <!-- End News -->

        <!-- Feedback Form -->
        <div class="g-position--relative g-bg-color--primary">
            <div class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
                <div class="g-text-center--xs g-margin-b-80--xs">
                    <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--white-opacity g-letter-spacing--2 g-margin-b-25--xs">Contato</p>
                    <h2 class="g-font-size-32--xs g-font-size-36--md g-font-family--playfair g-color--white">Entre em Contato</h2>
                </div>
                <div class="row g-row-col--5 g-margin-b-80--xs">
                    <div class="col-xs-4 g-full-width--xs g-margin-b-30--xs g-margin-b-0--sm">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".3s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-email"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Email</h4>
                                <p class="g-color--white-opacity">contato@fksc.com.br</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 g-full-width--xs g-margin-b-30--xs g-margin-b-0--sm">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".1s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-map-alt"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Endereço</h4>
                                <p class="g-color--white-opacity">Rua Luciano Carneiro Qd. 4 Lt. 1 Bairro Calixto Abrão</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 g-full-width--xs">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".3s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-headphone-alt"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Ligue</h4>
                                <p class="g-color--white-opacity">TIM - (62)9 8183-8021 </p>
                                <p class="g-color--white-opacity">Claro - (62)9 9133-1667 </p>
                                <p class="g-color--white-opacity">Vivo - (62)9 8582-9140 </p>
                            </div>
                        </div>
                    </div>
                </div>
                <form class="center-block g-width-500--sm g-width-550--md">
                    <div class="g-margin-b-30--xs">
                        <input type="text" class="form-control s-form-v3__input" placeholder="* Nome">
                    </div>
                    <div class="row g-row-col-5 g-margin-b-50--xs">
                        <div class="col-sm-6 g-margin-b-30--xs g-margin-b-0--md">
                            <input type="email" class="form-control s-form-v3__input" placeholder="* Email">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control s-form-v3__input" placeholder="* Telefone">
                        </div>
                    </div>
                    <div class="g-margin-b-80--xs">
                        <textarea class="form-control s-form-v3__input" rows="5" placeholder="* Sua mensagem"></textarea>
                    </div>
                    <div class="g-text-center--xs">
                        <button type="submit" class="text-uppercase s-btn s-btn--md s-btn--white-bg g-radius--50 g-padding-x-70--xs g-margin-b-20--xs">Envie</button>
                    </div>
                </form>
            </div>
            <img class="s-mockup-v2" src="{% static 'inicial/img/mockups/pencil-01.png' %}" alt="Mockup Image">
        </div>
        <!-- End Feedback Form -->
        <!--========== END PAGE CONTENT ==========-->


{% endblock %}

videos/templates/videos/index.html
{% extends 'inicial/base.html' %}
{% block head %}
    {% load staticfiles %}
{% endblock %}
{% block body %}

            <!--========== PROMO BLOCK ==========-->
        <div class="g-fullheight--xs js__parallax-window" style="background: url({% static 'inicial/img/1920x1080/videoempi.jpg' %}) 50% 0 no-repeat fixed; background-size: cover;">
            <div class="g-container--md g-ver-center--xs g-text-center--xs">
                <div class="g-margin-b-70--xs">
                    <h1 class="g-font-size-55--sm g-font-size-70--lg g-font-family--playfair g-color--primary g-margin-b-20--xs g-margin-b-40--sm">Assista os Katas Shotokan</h1>
                    <p class="g-font-size-18--xs g-font-size-20--sm g-font-size-24--lg g-color--white g-margin-b-0--xs">Você pode conferir vários katas e técnicas aqui. Não se esqueça, qualquer dúvida você deve perguntar ao seu professor.</p>
                </div>
                <a href="#js__scroll-to-section" class="text-uppercase s-btn s-btn-icon--md s-btn--primary-brd g-radius--50 g-padding-x-60--xs">Assita</a>
            </div>
            <a href="http://keenthemes.com/" class="s-scroll-to-section-v1--bc g-margin-b-15--xs">
                <span class="g-font-size-18--xs g-color--white ti-angle-double-down"></span>
                <p class="text-uppercase g-font-family--playfair g-color--white g-letter-spacing--3 g-margin-b-0--xs">Confira os Vídeos</p>
            </a>
        </div>
        <!--========== END PROMO BLOCK ==========-->

        <!--========== PAGE CONTENT ==========-->
    <!-- Inicio dos Videos -->
    <br><br><br><br>
    <div class="container">
    <h2 class="g-font-size-32--xs g-font-size-36--md">CLIQUE NO NOME DO VIDEO E ASSISTA!</h2>
    <br><br>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {% for video in todos_videos %}
                <a href="{{ video.link }}"> <h1 class="btn-default text-uppercase" style="color:blue">{{video.titulo}}</h1></a>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Final dos Videos -->

    <!-- News -->
        <div class="container g-padding-y-80--xs g-padding-y-125--sm">
            <div class="g-text-center--xs g-margin-b-80--xs">
                <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2 g-margin-b-25--xs">Blog</p>
                <h2 class="g-font-size-32--xs g-font-size-36--md">Últimas Notícias</h2>
            </div>
            <div class="row">
                <div class="col-sm-4 g-margin-b-30--xs g-margin-b-0--md">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/1920x1080/copadapaz.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Notícias</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'campeonatos:index' %}">IX Copa da Paz.</a></h3>
                            <p>Um campeonato de magnitude Internacional que será sediado no Brasil.</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
                <div class="col-sm-4 g-margin-b-30--xs g-margin-b-0--md">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/1920x1080/filie.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Informativos</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'filiados:atletas' %}">Como me filiar?</a></h3>
                            <p>E agora? Desejo me filiar ou filiar os meus alunos, como faço? Clica e descubra</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
                <div class="col-sm-4">
                    <!-- News -->
                    <article>
                        <img class="img-responsive" src="{% static 'inicial/img/970x970/brasileiro2017.png' %}" alt="Image">
                        <div class="g-bg-color--white g-box-shadow__dark-lightest-v2 g-text-center--xs g-padding-x-40--xs g-padding-y-40--xs">
                            <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--primary g-letter-spacing--2">Notícias</p>
                            <h3 class="g-font-size-22--xs g-letter-spacing--1"><a href="{% url 'campeonatos:index' %}">XXI Campeonato Brasileiro Inter Clubes.</a></h3>
                            <p>Descubra o sucesso que foi participar do Campeonato Brasileiro de 2017.</p>
                        </div>
                    </article>
                    <!-- End News -->
                </div>
            </div>
        </div>
        <!-- End News -->

        <!-- Feedback Form -->
        <div class="g-position--relative g-bg-color--primary">
            <div class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
                <div class="g-text-center--xs g-margin-b-80--xs">
                    <p class="text-uppercase g-font-size-14--xs g-font-weight--700 g-color--white-opacity g-letter-spacing--2 g-margin-b-25--xs">Contato</p>
                    <h2 class="g-font-size-32--xs g-font-size-36--md g-font-family--playfair g-color--white">Entre em Contato</h2>
                </div>
                <div class="row g-row-col--5 g-margin-b-80--xs">
                    <div class="col-xs-4 g-full-width--xs g-margin-b-30--xs g-margin-b-0--sm">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".3s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-email"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Email</h4>
                                <p class="g-color--white-opacity">contato@fksc.com.br</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 g-full-width--xs g-margin-b-30--xs g-margin-b-0--sm">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".1s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-map-alt"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Endereço</h4>
                                <p class="g-color--white-opacity">Rua Luciano Carneiro Qd. 4 Lt. 1 Bairro Calixto Abrão</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-4 g-full-width--xs">
                        <div class="wow fadeInUp" data-wow-duration=".3" data-wow-delay=".3s">
                            <div class="g-text-center--xs">
                                <i class="g-display-block--xs g-font-size-40--xs g-color--white-opacity g-margin-b-30--xs ti-headphone-alt"></i>
                                <h4 class="g-font-size-18--xs g-font-family--playfair g-color--white g-margin-b-5--xs">Ligue</h4>
                                <p class="g-color--white-opacity">TIM - (62)9 8183-8021 </p>
                                <p class="g-color--white-opacity">Claro - (62)9 9133-1667 </p>
                                <p class="g-color--white-opacity">Vivo - (62)9 8582-9140 </p>
                            </div>
                        </div>
                    </div>
                </div>
                <form class="center-block g-width-500--sm g-width-550--md">
                    <div class="g-margin-b-30--xs">
                        <input type="text" class="form-control s-form-v3__input" placeholder="* Nome">
                    </div>
                    <div class="row g-row-col-5 g-margin-b-50--xs">
                        <div class="col-sm-6 g-margin-b-30--xs g-margin-b-0--md">
                            <input type="email" class="form-control s-form-v3__input" placeholder="* Email">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control s-form-v3__input" placeholder="* Telefone">
                        </div>
                    </div>
                    <div class="g-margin-b-80--xs">
                        <textarea class="form-control s-form-v3__input" rows="5" placeholder="* Sua mensagem"></textarea>
                    </div>
                    <div class="g-text-center--xs">
                        <button type="submit" class="text-uppercase s-btn s-btn--md s-btn--white-bg g-radius--50 g-padding-x-70--xs g-margin-b-20--xs">Envie</button>
                    </div>
                </form>
            </div>
            <img class="s-mockup-v2" src="{% static 'inicial/img/mockups/pencil-01.png' %}" alt="Mockup Image">
        </div>
        <!-- End Feedback Form -->
        <!--========== END PAGE CONTENT ==========-->


{% endblock %}